Repository ASFHyP3/hyp3-lib, pull requests merged in 2020-07, with the labels that each got.

#176 Publish releases on PyPI.org
  .github/workflows/test-and-build.yml
Labels: CI/CD

#178 Drop low-res (1024) browse images
  hyp3lib/makeAsfBrowse.py
  tests/conftest.py
  tests/data/test_geotiff.tif
  tests/test_make_asf_browse.py
Labels: enhancement

#177 Update to pyproj 2 style syntax
  conda-env.yml
  hyp3lib/get_dem.py
  setup.py
Labels: bug

#180 Release
  .github/workflows/release.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  conda-env.yml
  hyp3lib/etc/bin/repackage_into_cogs.sh
  hyp3lib/get_dem.py
  hyp3lib/makeAsfBrowse.py
  hyp3lib/make_cogs.py
  setup.py
  tests/conftest.py
  tests/data/test_geotiff.tif
  tests/test_make_asf_browse.py
  tests/test_make_cogs.py
Labels: minor

#181 Pulling refs/tags/v1.3.0 into default
  .github/workflows/release.yml
  CHANGELOG.md
Labels: tools-bot

#182 Project meta
  .github/pull_request_template.md
  .github/workflows/release.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  README.md
  setup.py
Labels: CI/CD, bug

#183 Allow upfront downloading of orbit files
  .github/workflows/test-and-build.yml
  conda-env.yml
  hyp3lib/__init__.py
  hyp3lib/exceptions.py
  hyp3lib/fetch.py
  hyp3lib/get_orb.py
  hyp3lib/ingest_S1_granule.py
  hyp3lib/par_s1_slc_single.py
  setup.py
  tests/conftest.py
  tests/test_entrypoints.py
  tests/test_fetch.py
  tests/test_get_orb.py
Labels: enhancement

#185 get_orb bugfixes
  hyp3lib/get_orb.py
Labels: bug

#184 Release upfront orbit fetching
  .github/pull_request_template.md
  .github/workflows/release.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  README.md
  conda-env.yml
  hyp3lib/__init__.py
  hyp3lib/exceptions.py
  hyp3lib/fetch.py
  hyp3lib/get_orb.py
  hyp3lib/ingest_S1_granule.py
  hyp3lib/par_s1_slc_single.py
  setup.py
  tests/conftest.py
  tests/test_entrypoints.py
  tests/test_fetch.py
  tests/test_get_orb.py
Labels: minor

#186 Change orbit error logging
  hyp3lib/get_orb.py
  hyp3lib/ingest_S1_granule.py
  hyp3lib/par_s1_slc_single.py
Labels: enhancement

#188 Release: get_orb revisions
  CHANGELOG.md
  hyp3lib/get_orb.py
  hyp3lib/ingest_S1_granule.py
  hyp3lib/par_s1_slc_single.py
Labels: enhancement, patch

#191 Don't duplicate conda channels
  .github/workflows/test-and-build.yml
Labels: CI/CD
