Repository ASFHyP3/hyp3-lib, pull requests merged in 2023-11, with the labels that each got.

#278 Proposed README changes
  README.md
Labels: bumpless

#277 Update Changelog
  CHANGELOG.md
Labels: bumpless

#276 Release v2.0.0
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/queries/associated-pr.query.yml
  .github/queries/pr-labels.query.yml
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test.yml
  .gitleaks.toml
  CHANGELOG.md
  README.md
  environment.yml
  hyp3lib/fetch.py
  hyp3lib/get_orb.py
  setup.py
  tests/test_get_orb.py
Labels: major

#280 Update distribute action
  .github/workflows/distribute.yml
  CHANGELOG.md
Labels: patch

#281 Add `build` to `environment.yml`
  .github/workflows/distribute.yml
  environment.yml
Labels: bumpless

#282 Release v2.0.2
  .github/workflows/distribute.yml
  CHANGELOG.md
  environment.yml
Labels: patch
